In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm

In [2]:
Type = 'Testing'

In [3]:
DATADIR = 'C:/Users/C1764397/Workshop/PhD/Data/FractalClusters/{}/features'.format(Type)

In [4]:
labels = np.loadtxt('C:/Users/C1764397/Workshop/PhD/Data/FractalClusters/{}/labels/labels.txt'.format(Type))

In [5]:
training_data = []
c=0

for img in tqdm(os.listdir(DATADIR)):
    img_array = cv2.imread(os.path.join(DATADIR,img))
    new_array = cv2.resize(img_array, (200,200))
    training_data.append([new_array,labels[c]])
    c+=1
    
print(len(training_data))
    

100%|█████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:08<00:00, 230.05it/s]


2000


In [6]:
import random
random.shuffle(training_data)

In [7]:
for sample in training_data[:10]:
    print(sample[1])

[   0.32623853    2.82868288  260.        ]
[   0.5243048     1.90038763  293.        ]
[  2.27697464e-02   1.31918214e+00   4.13000000e+02]
[   0.25448646    2.91306142  104.        ]
[   0.37035067    2.87656819  276.        ]
[  3.85397631e-01   1.32011476e+00   4.33000000e+02]
[  1.76291845e-01   9.45645197e-01   2.40000000e+02]
[   0.55307925    2.32693511  223.        ]
[   0.71123063    1.17527411  159.        ]
[   0.52248081    0.3471627   283.        ]


In [8]:
X=[]
H=[]
sigma=[]
pop=[]

for features,labels in training_data:
    X.append(features)
    H.append(labels[0])
    sigma.append(labels[1])
    pop.append(labels[2])
    
y=[H,sigma,pop]

#print(X[0].reshape(-1, 200, 200, 3, 1))

#print(y)


X=np.array(X).reshape(-1,200,200,3)
print(X.shape)

(2000, 200, 200, 3)


In [9]:
import pickle

pickle_out = open("C:/Users/C1764397/Workshop/PhD/Data/FractalClusters/{}/X_{}.pickle".format(Type,Type),"wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("C:/Users/C1764397/Workshop/PhD/Data/FractalClusters/{}/y_{}.pickle".format(Type,Type),"wb")
pickle.dump(y, pickle_out)
pickle_out.close()